const sessionData = [
  {
    id: "1",
    name: "Opening Keynote: The Future of Startups",
    registered: 1248,
    attended: 1052,
    engagement: 93,
    feedback: 4.8,
    time: "9:00 AM - 10:00 AM",
    location: "Main Stage",
    status: "completed",
  },
  {
    id: "2",
    name: "Workshop: MVPs That Win Investors",
    registered: 460,
    attended: 389,
    engagement: 87,
    feedback: 4.6,
    time: "10:30 AM - 12:00 PM",
    location: "Startup Lab A",
    status: "completed",
  },
  {
    id: "3",
    name: "Workshop: Scaling Your Startup Team",
    registered: 430,
    attended: 374,
    engagement: 84,
    feedback: 4.7,
    time: "10:30 AM - 12:00 PM",
    location: "Startup Lab B",
    status: "completed",
  },
  {
    id: "4",
    name: "Panel: Fundraising in 2025",
    registered: 890,
    attended: 755,
    engagement: 91,
    feedback: 4.5,
    time: "1:00 PM - 2:30 PM",
    location: "Main Stage",
    status: "completed",
  },
  {
    id: "5",
    name: "Networking: Meet the Founders",
    registered: 970,
    attended: 882,
    engagement: 80,
    feedback: 4.3,
    time: "3:00 PM - 4:30 PM",
    location: "Networking Lounge",
    status: "in-progress",
  },
  {
    id: "6",
    name: "Closing Ceremony: Startup Lessons Learned",
    registered: 1120,
    attended: 0,
    engagement: 0,
    feedback: 0,
    time: "5:00 PM - 5:30 PM",
    location: "Main Stage",
    status: "upcoming",
  },
];

export default sessionData;
